# Generated by Django 3.2.2 on 2021-05-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_auto_20210508_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointhits',
            name='query_params',
            field=models.JSONField(default=None),
        ),
    ]
